version: '3.8'

services:
  db:
    build: ./database
    container_name: jkpg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jkpg-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jkpg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    container_name: jkpg-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app  # Mount backend code
      - /usr/src/app/node_modules  # Prevent overwriting node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jkpg-network

  frontend:
    build: ./frontend
    container_name: jkpg-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html  # Mount frontend code
    depends_on:
      - backend
    networks:
      - jkpg-network

volumes:
  db_data:

networks:
  jkpg-network:
    driver: bridge